name: Branch Checks
description: Action to run branch checks for code consistency

runs:
  using: composite
  steps:
    - name: Format Check
      shell: bash
      run: pnpm format:check
    - name: Lint Check
      shell: bash
      run: pnpm lint

    # Add additional branch checks here.
    # i.e. Translations, security checks, and any other additional checks
